from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    file = Path(path)
    text = file.read_text()
    if old not in text:
        raise SystemExit(f"marker missing in {path}: {old[:120]!r}")
    file.write_text(text.replace(old, new, 1))


# roles-access-admin-service.ts
path = "src/application/roles-access-admin-service.ts"
replace_once(path, "  assignedMembers: readonly string[];\n}", "  assignedMembers: readonly string[];\n  retiredAt?: string;\n}")
replace_once(path, "export interface AccessMutationResult {", "export interface RetireCustomWorkspaceRoleCommand {\n  tenantId: string;\n  workspaceId: string;\n  roleDefinitionId: string;\n  actorSubjectId: string;\n  auditEventId: string;\n  occurredAt: string;\n}\n\nexport interface AccessMutationResult {")
replace_once(path, "  isSystem: number;\n}\n\ninterface MemberRow", "  isSystem: number;\n  retiredAt: string | null;\n}\n\ninterface MemberRow")
replace_once(path, "                role.permissions_json AS permissionsJson,\n                role.is_system AS isSystem\n", "                role.permissions_json AS permissionsJson,\n                role.is_system AS isSystem,\n                role.retired_at AS retiredAt\n")
replace_once(path, "          assignedMembers: impacts.map(\n            (impact) => `${impact.subjectName} — ${impact.workspaceName}`,\n          ),\n", "          assignedMembers: impacts.map(\n            (impact) => `${impact.subjectName} — ${impact.workspaceName}`,\n          ),\n          retiredAt: role.retiredAt ?? undefined,\n")
replace_once(path, "    const name = normalizeRoleName(command.name);\n    const permissions = normalizeCustomPermissions(command.permissions);\n", "    if (current.retiredAt) {\n      throw new Error(\"Retired custom roles cannot be edited.\");\n    }\n    const name = normalizeRoleName(command.name);\n    const permissions = normalizeCustomPermissions(command.permissions);\n", )
# The previous replacement must target update, not create. Correct accidental create insertion if present.
text = Path(path).read_text()
create_bad = "  public async createCustomWorkspaceRole(\n    command: CreateCustomWorkspaceRoleCommand,\n  ): Promise<AccessMutationResult> {\n    await this.loadWorkspace(command.tenantId, command.workspaceId);\n    if (current.retiredAt) {\n      throw new Error(\"Retired custom roles cannot be edited.\");\n    }\n"
if create_bad in text:
    text = text.replace(create_bad, "  public async createCustomWorkspaceRole(\n    command: CreateCustomWorkspaceRoleCommand,\n  ): Promise<AccessMutationResult> {\n    await this.loadWorkspace(command.tenantId, command.workspaceId);\n", 1)
    update_marker = "    const current = await this.loadCustomWorkspaceRole(\n      command.tenantId,\n      command.roleDefinitionId,\n    );\n"
    if update_marker not in text:
        raise SystemExit("update current marker missing")
    text = text.replace(update_marker, update_marker + "    if (current.retiredAt) {\n      throw new Error(\"Retired custom roles cannot be edited.\");\n    }\n", 1)
Path(path).write_text(text)
retire_method = '''\n  public async retireCustomWorkspaceRole(\n    command: RetireCustomWorkspaceRoleCommand,\n  ): Promise<AccessMutationResult> {\n    await this.loadWorkspace(command.tenantId, command.workspaceId);\n    const current = await this.loadCustomWorkspaceRole(\n      command.tenantId,\n      command.roleDefinitionId,\n    );\n    if (current.retiredAt) {\n      return {\n        changed: false,\n        snapshot: await this.getWorkspaceAccess(\n          command.tenantId,\n          command.workspaceId,\n        ),\n      };\n    }\n\n    const [impact] = await this.database.query<{ assignmentCount: number }>(\n      `SELECT COUNT(*) AS assignmentCount\n       FROM role_bindings\n       WHERE role_definition_id = ? AND tenant_id = ?`,\n      [command.roleDefinitionId, command.tenantId],\n    );\n    const assignmentCount = Number(impact?.assignmentCount ?? 0);\n    if (assignmentCount > 0) {\n      throw new Error(\n        `Remove all ${assignmentCount} current assignment${assignmentCount === 1 ? \"\" : \"s\"} before retiring this custom role.`,\n      );\n    }\n\n    await this.database.executeBatch([\n      statement(\n        `UPDATE role_definitions\n         SET retired_at = ?\n         WHERE id = ? AND tenant_id = ? AND scope = 'workspace' AND is_system = 0`,\n        [command.occurredAt, command.roleDefinitionId, command.tenantId],\n      ),\n      auditStatement({\n        id: command.auditEventId,\n        tenantId: command.tenantId,\n        workspaceId: command.workspaceId,\n        actorSubjectId: command.actorSubjectId,\n        eventType: \"role.definition.retired\",\n        entityType: \"role_definition\",\n        entityId: command.roleDefinitionId,\n        occurredAt: command.occurredAt,\n        payload: {\n          roleKey: current.roleKey,\n          name: current.name,\n          permissions: JSON.stringify(parsePermissionList(current.permissionsJson)),\n          retirement: \"terminal\",\n        },\n      }),\n    ]);\n\n    return {\n      changed: true,\n      snapshot: await this.getWorkspaceAccess(\n        command.tenantId,\n        command.workspaceId,\n      ),\n    };\n  }\n'''
replace_once(path, "\n  public async assignWorkspaceRole(\n", retire_method + "\n  public async assignWorkspaceRole(\n")
replace_once(path, "              permissions_json AS permissionsJson,\n              is_system AS isSystem\n       FROM role_definitions\n       WHERE id = ?\n         AND scope = 'workspace'\n         AND (tenant_id IS NULL OR tenant_id = ?)", "              permissions_json AS permissionsJson,\n              is_system AS isSystem,\n              retired_at AS retiredAt\n       FROM role_definitions\n       WHERE id = ?\n         AND scope = 'workspace'\n         AND retired_at IS NULL\n         AND (tenant_id IS NULL OR tenant_id = ?)")
replace_once(path, "              permissions_json AS permissionsJson,\n              is_system AS isSystem\n       FROM role_definitions\n       WHERE id = ?\n         AND tenant_id = ?", "              permissions_json AS permissionsJson,\n              is_system AS isSystem,\n              retired_at AS retiredAt\n       FROM role_definitions\n       WHERE id = ?\n         AND tenant_id = ?")

# authorized wrapper
path = "src/application/authorized-roles-access-admin-service.ts"
replace_once(path, "  RemoveWorkspaceRoleCommand,\n", "  RemoveWorkspaceRoleCommand,\n  RetireCustomWorkspaceRoleCommand,\n")
method = '''\n  public async retireCustomWorkspaceRole(\n    context: RolesAccessAuthorizationContext,\n    command: Omit<\n      RetireCustomWorkspaceRoleCommand,\n      \"tenantId\" | \"workspaceId\" | \"actorSubjectId\"\n    >,\n  ): Promise<AccessMutationResult> {\n    await this.assertTenantRoleDefinitionManagementAllowed(context);\n    return this.access.retireCustomWorkspaceRole({\n      ...command,\n      tenantId: context.tenantId,\n      workspaceId: context.workspaceId,\n      actorSubjectId: context.subjectId,\n    });\n  }\n'''
replace_once(path, "\n  public async assignWorkspaceRole(\n", method + "\n  public async assignWorkspaceRole(\n")

# input parser
path = "src/application/roles-access-input.ts"
retire_parser = '''\nexport function parseCustomRoleRetirementInput(values: URLSearchParams): {\n  roleDefinitionId: string;\n} {\n  return {\n    roleDefinitionId: requiredIdentifier(\n      values,\n      \"roleDefinitionId\",\n      \"Custom role\",\n    ),\n  };\n}\n'''
replace_once(path, "\nfunction requiredRoleName", retire_parser + "\nfunction requiredRoleName")

# domain model
path = "src/domain/models.ts"
replace_once(path, "  isSystem: boolean;\n  createdAt: IsoTimestamp;\n}", "  isSystem: boolean;\n  createdAt: IsoTimestamp;\n  retiredAt?: IsoTimestamp;\n}")

# portable export
path = "src/application/portable-export-read-service.ts"
replace_once(path, "  isSystem: number;\n  createdAt: string;\n}", "  isSystem: number;\n  createdAt: string;\n  retiredAt: string | null;\n}")
replace_once(path, "              is_system AS isSystem,\n              created_at AS createdAt\n", "              is_system AS isSystem,\n              created_at AS createdAt,\n              retired_at AS retiredAt\n")
replace_once(path, "      isSystem: row.isSystem === 1,\n      createdAt: row.createdAt,\n", "      isSystem: row.isSystem === 1,\n      createdAt: row.createdAt,\n      retiredAt: row.retiredAt ?? undefined,\n")

# export validator
path = "src/application/export.ts"
replace_once(path, "    if (![\"platform\", \"tenant\", \"workspace\"].includes(role.scope)) {\n      throw new Error(`Role definition ${role.id} has an invalid scope.`);\n    }\n", "    if (![\"platform\", \"tenant\", \"workspace\"].includes(role.scope)) {\n      throw new Error(`Role definition ${role.id} has an invalid scope.`);\n    }\n    if (role.retiredAt !== undefined) {\n      requireString(role.retiredAt, `role definition ${role.id} retiredAt`);\n      if (role.isSystem || role.scope !== \"workspace\" || !role.tenantId) {\n        throw new Error(\n          `Only tenant-owned custom workspace roles may be retired (${role.id}).`,\n        );\n      }\n    }\n")

# e2e migration list
path = "scripts/e2e-d1.ts"
marker = '''    readFile(\n      new URL(\n        \"../migrations/0006_workflow_definition_lifecycle.sql\",\n        import.meta.url,\n      ),\n      \"utf8\",\n    ),\n'''
addition = marker + '''    readFile(\n      new URL(\n        \"../migrations/0007_custom_role_retirement.sql\",\n        import.meta.url,\n      ),\n      \"utf8\",\n    ),\n'''
replace_once(path, marker, addition)

# index imports / notice / route
path = "src/index.ts"
replace_once(path, "  parseCustomRoleCreateInput,\n  parseCustomRoleUpdateInput,\n", "  parseCustomRoleCreateInput,\n  parseCustomRoleRetirementInput,\n  parseCustomRoleUpdateInput,\n")
replace_once(path, '            : noticeValue === "role-updated"\n              ? "Custom workspace role updated."\n              : noticeValue === "unchanged"', '            : noticeValue === "role-updated"\n              ? "Custom workspace role updated."\n              : noticeValue === "role-retired"\n                ? "Custom workspace role retired."\n                : noticeValue === "unchanged"')
route = '''\napp.post(\"/demo/app/admin/access/roles/retire\", async (context) => {\n  if (!guidedDemoEnabled(context.env)) return context.notFound();\n  if (!hasSameOrigin(context.req.url, context.req.header(\"Origin\"))) {\n    return context.json({ error: \"Same-origin demo request required.\" }, 403);\n  }\n  const sessionId = readGuidedDemoSession(context.req.header(\"Cookie\"));\n  if (!sessionId) {\n    return context.json(\n      {\n        error:\n          \"Synthetic administration session missing. Reload Roles & Access.\",\n      },\n      409,\n    );\n  }\n\n  try {\n    const input = parseCustomRoleRetirementInput(\n      await readFormValues(context.req.raw, [\"roleDefinitionId\"]),\n    );\n    const database = new D1DatabaseProvider(context.env.DOCUMENT_CONTROL_DB);\n    const demo = createGuidedDemoContext(sessionId);\n    await ensureGuidedDemoSeed(database, sessionId);\n    const admin = await ensureGuidedTenantAdmin(database, sessionId);\n    const result = await createAuthorizedRolesAccessAdminService(\n      database,\n    ).retireCustomWorkspaceRole(\n      {\n        subjectId: admin.subjectId,\n        tenantId: demo.tenantId,\n        workspaceId: demo.workspaceId,\n      },\n      {\n        roleDefinitionId: input.roleDefinitionId,\n        auditEventId: `role-definition-audit-${crypto.randomUUID()}`,\n        occurredAt: new Date().toISOString(),\n      },\n    );\n    return context.redirect(\n      `/demo/app/admin/access?notice=${result.changed ? \"role-retired\" : \"unchanged\"}`,\n      303,\n    );\n  } catch (error) {\n    if (error instanceof RolesAccessInputValidationError) {\n      return context.text(error.message, 400);\n    }\n    if (error instanceof AuthorizationDeniedError) {\n      return context.html(renderNotFound(createTheme(context.env)), 404);\n    }\n    return context.text(\n      error instanceof Error ? error.message : \"Custom role retirement failed.\",\n      409,\n    );\n  }\n});\n'''
replace_once(path, "\napp.get(\"/demo/app/admin/workflows\"", route + "\napp.get(\"/demo/app/admin/workflows\"")

# roles UI
path = "src/ui/render-roles-access-admin.ts"
replace_once(path, "  const systemRoles = snapshot.roles.filter((role) => role.isSystem);\n  const customRoles = snapshot.roles.filter((role) => !role.isSystem);\n", "  const systemRoles = snapshot.roles.filter((role) => role.isSystem);\n  const customRoles = snapshot.roles.filter((role) => !role.isSystem);\n  const assignableRoles = snapshot.roles.filter((role) => !role.retiredAt);\n")
replace_once(path, "        <li>Built-in system roles remain immutable. Custom roles can use only the bounded operational permissions shown below.</li>\n", "        <li>Built-in system roles remain immutable. Custom roles can use only the bounded operational permissions shown below.</li>\n        <li>Custom-role retirement is terminal and non-destructive: all assignments must be removed first, then the retired definition remains available for audit/export history but cannot be edited or assigned again.</li>\n")
replace_once(path, '${snapshot.roles.length} eligible role${snapshot.roles.length === 1 ? "" : "s"}', '${assignableRoles.length} eligible role${assignableRoles.length === 1 ? "" : "s"}')
replace_once(path, '${snapshot.roles.map((role) => `<option value="${escapeHtml(role.id)}">${escapeHtml(role.name)}${role.isSystem ? "" : " — custom"}</option>`).join("")}', '${assignableRoles.map((role) => `<option value="${escapeHtml(role.id)}">${escapeHtml(role.name)}${role.isSystem ? "" : " — custom"}</option>`).join("")}')
old_editor = '''function renderCustomRoleEditor(role: AccessRoleDefinition): string {\n  const impact =\n    role.assignmentCount === 0\n      ? '<p class="impact clear">No current tenant assignments use this role.</p>'\n      : `<div class="impact"><strong>${role.assignmentCount} current tenant assignment${role.assignmentCount === 1 ? "" : "s"} will be affected by changes:</strong><ul>${role.assignedMembers.map((member) => `<li>${escapeHtml(member)}</li>`).join("")}</ul></div>`;\n  const acknowledgement =\n    role.assignmentCount === 0\n      ? ""\n      : `<label class="ack"><input type="checkbox" name="acknowledgeAssignments" value="yes" required> I understand this change affects the current assignments listed above.</label>`;\n  return `<article class="custom-role-card">\n    <div class="role-heading"><div><p class="eyebrow">Custom role</p><h3>${escapeHtml(role.name)}</h3></div><code>${escapeHtml(role.key)}</code></div>\n    ${impact}\n    <form method="post" action="/demo/app/admin/access/roles/update" class="role-form">\n      <input type="hidden" name="roleDefinitionId" value="${escapeHtml(role.id)}">\n      <label>Role name\n        <input name="name" required minlength="2" maxlength="80" value="${escapeHtml(role.name)}" autocomplete="off">\n      </label>\n      ${permissionFieldset(role.permissions)}\n      ${acknowledgement}\n      <button type="submit">Save custom role</button>\n    </form>\n  </article>`;\n}\n'''
new_editor = '''function renderCustomRoleEditor(role: AccessRoleDefinition): string {\n  if (role.retiredAt) {\n    return `<article class="custom-role-card">\n      <div class="role-heading"><div><p class="eyebrow">Retired custom role</p><h3>${escapeHtml(role.name)}</h3></div><code>${escapeHtml(role.key)}</code></div>\n      <p class="impact clear"><strong>Retired ${escapeHtml(role.retiredAt)}</strong> · historical definition only. It cannot be edited, reactivated, or assigned to new members.</p>\n      <p class="muted">Permissions retained for audit/export history: ${role.permissions.map(escapeHtml).join(", ")}</p>\n    </article>`;\n  }\n\n  const impact =\n    role.assignmentCount === 0\n      ? '<p class="impact clear">No current tenant assignments use this role.</p>'\n      : `<div class="impact"><strong>${role.assignmentCount} current tenant assignment${role.assignmentCount === 1 ? "" : "s"} will be affected by changes:</strong><ul>${role.assignedMembers.map((member) => `<li>${escapeHtml(member)}</li>`).join("")}</ul></div>`;\n  const acknowledgement =\n    role.assignmentCount === 0\n      ? ""\n      : `<label class="ack"><input type="checkbox" name="acknowledgeAssignments" value="yes" required> I understand this change affects the current assignments listed above.</label>`;\n  const retirement =\n    role.assignmentCount === 0\n      ? `<form method="post" action="/demo/app/admin/access/roles/retire" class="retire-form"><input type="hidden" name="roleDefinitionId" value="${escapeHtml(role.id)}"><p class="muted">Retirement is terminal. The definition remains in audit/export history but cannot be assigned or edited again.</p><button class="secondary" type="submit">Retire custom role</button></form>`\n      : '<p class="muted"><strong>Retirement unavailable:</strong> remove every tenant assignment for this role first.</p>';\n  return `<article class="custom-role-card">\n    <div class="role-heading"><div><p class="eyebrow">Custom role</p><h3>${escapeHtml(role.name)}</h3></div><code>${escapeHtml(role.key)}</code></div>\n    ${impact}\n    <form method="post" action="/demo/app/admin/access/roles/update" class="role-form">\n      <input type="hidden" name="roleDefinitionId" value="${escapeHtml(role.id)}">\n      <label>Role name\n        <input name="name" required minlength="2" maxlength="80" value="${escapeHtml(role.name)}" autocomplete="off">\n      </label>\n      ${permissionFieldset(role.permissions)}\n      ${acknowledgement}\n      <button type="submit">Save custom role</button>\n    </form>\n    ${retirement}\n  </article>`;\n}\n'''
replace_once(path, old_editor, new_editor)
replace_once(path, ".custom-role-card{border:1px solid var(--border);background:var(--surface);border-radius:14px;padding:1rem}", ".custom-role-card{border:1px solid var(--border);background:var(--surface);border-radius:14px;padding:1rem}.retire-form{margin-top:1rem;padding-top:1rem;border-top:1px solid var(--border)}")
